### ISSUE TITLE
Look at databases and make suggestions for the project for a focus

### ISSUE THREAD

**Issue by NanaSandberg** [jamadaha/P5#10]

**Comment by kris701** [comment]
Potential datasets
* [Something with letter recognition](https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits)
  - We can also simply make our own set
* [Car evaluation](https://archive.ics.uci.edu/ml/datasets/Car+Evaluation)
* [Energy Effeciency](https://archive.ics.uci.edu/ml/datasets/Energy+efficiency)

**Comment by AnjaLumholtz** [comment]
[Amazon Review Set](https://archive.ics.uci.edu/ml/datasets/Amazon+Commerce+reviews+set) 

[SMS spam collection set](https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection)

[Youtube spam collection data set](https://archive.ics.uci.edu/ml/datasets/YouTube+Spam+Collection)

**Comment by jamadaha** [comment]
https://www.kaggle.com/landlord/handwriting-recognition

Handwritten names
