### ISSUE TITLE
Find dataset with handwritten text (Small pictures)

### ISSUE THREAD

**Issue by kris701** [jamadaha/P5#12]

**Comment by jamadaha** [comment]
https://github.com/jamadaha/P5/issues/10#issuecomment-923678784
> https://www.kaggle.com/landlord/handwriting-recognition
> 
> Handwritten names

**Comment by jamadaha** [comment]
https://www.linkedin.com/pulse/15-best-ocr-handwriting-datasets-machine-learning-limarc-ambalina
A couple of datasets with text

https://www.nist.gov/itl/products-and-services/emnist-dataset#:~:text=The%20EMNIST%20dataset%20is%20a,directly%20matches%20the%20MNIST%20dataset%20
Emnist data

**Comment by jamadaha** [comment]
https://www.nist.gov/srd/nist-special-database-19
Dataset of PNG images of format 128x128. It contains digits, lowercase and uppercase letters.
