### ISSUE TITLE
JANGANQueue throws an error when finished

### ISSUE THREAD

**Issue by kris701** [jamadaha/P5#123]
**Describe the bug**
It seems that the JANGANQueue throws an exception when its finished running the queue

**To Reproduce**
Just run the queue

**Expected behavior**
To not throw an error

**Screenshots**
![image](https://user-images.githubusercontent.com/22596587/141425620-60726b88-d65c-49da-9c00-8e15eee48bda.png)

**Desktop (please complete the following information):**

- [ ] Windows
- [X] Linux

**Comment by jamadaha** [comment]
This bug comes from writing -m when running the project from terminal. As JANGANQueue isn't a module.
