### ISSUE TITLE
Potential error in the output images of the DataGenerator

### ISSUE THREAD

**Issue by kris701** [jamadaha/P5#95]
**Describe the bug**
I have noticed that some of the images from the Data Generator sometimes have been cut in half. I am unsuer if this is just how the data is in the first place, but it seems a bit weird

**To Reproduce**
Just produce any images with the Data Generator

**Expected behavior**
Just a direct copy of the images from the Zip file

**Screenshots**
Here are some examples where it looks like the image have been cut a little
![9](https://user-images.githubusercontent.com/22596587/140271853-dc23e2d2-73d5-4306-a37e-83bfba253152.png)
![6](https://user-images.githubusercontent.com/22596587/140271921-0b78f278-d3b0-4a3c-9c6f-8d820353e159.png)
![5](https://user-images.githubusercontent.com/22596587/140271973-b8c31bae-c5d6-4c11-8f33-6b4e9639d541.png)

**Desktop (please complete the following information):**

- [X] Windows
- [ ] Linux

**Comment by jamadaha** [comment]
This is a problem with the data itself, see by_class/67/hsf_7/hsf_7_00001.png
